name: CI Pipeline

on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: windows-latest
        
        steps:
            - name: setup-msbuild
              uses: microsoft/setup-msbuild@v1
              
            - name: Run a one-line script
              run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /help'